# Generated by Django 3.1.3 on 2021-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='solved',
            field=models.ImageField(default=models.ImageField(upload_to=''), upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
