# Generated by Django 3.1.3 on 2021-02-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0002_auto_20210201_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='solved',
        ),
    ]
