# Generated by Django 3.1.3 on 2021-02-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0003_remove_image_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='solved',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
